# Generated by Django 4.1.4 on 2023-01-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='adhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=500)),
                ('adno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.adhar')),
            ],
        ),
    ]
