# Generated by Django 4.1.4 on 2023-01-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_adhar_reports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reports',
        ),
    ]
