# Generated by Django 4.1.4 on 2023-01-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='pdff',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
