# Generated by Django 4.1.4 on 2023-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_reports_pdff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='pdff',
        ),
    ]
