# Generated by Django 4.1.4 on 2023-01-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_reports_pdff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='adno',
            field=models.CharField(max_length=12),
        ),
    ]
