# Generated by Django 4.1.4 on 2023-01-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_reports_adno'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='dat',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AddField(
            model_name='reports',
            name='diag',
            field=models.CharField(default='0000000', max_length=500),
        ),
        migrations.AddField(
            model_name='reports',
            name='prec',
            field=models.CharField(default='0000000000000', max_length=1000),
        ),
    ]
