# Generated by Django 4.1.4 on 2023-01-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reports_dat_reports_diag_reports_prec'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='remarks',
            field=models.CharField(default='000000000', max_length=1000),
        ),
    ]
