# Generated by Django 4.1.4 on 2023-01-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_reports_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='remarks',
            new_name='rem',
        ),
    ]
