# Generated by Django 4.1.4 on 2023-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_tempreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=50)),
                ('adno', models.CharField(max_length=12)),
            ],
        ),
    ]
