# Generated by Django 4.1.4 on 2023-01-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_passwd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passwd',
            new_name='pad',
        ),
    ]
